import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Check, ImagePlus, Loader2, UserRound } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useLocation } from "wouter";

export default function Profile() {
  const { user, loading, isAuthenticated } = useAuth();
  const [, setLocation] = useLocation();
  const [name, setName] = useState("");
  const [avatarUrl, setAvatarUrl] = useState("");
  const fileRef = useRef<HTMLInputElement>(null);
  const utils = trpc.useUtils();
  const update = trpc.profile.update.useMutation({ onSuccess: async () => { await utils.auth.me.invalidate(); window.alert("Profile saved"); } });
  const uploadAvatar = trpc.profile.uploadAvatar.useMutation({ onSuccess: async ({ url }) => { setAvatarUrl(url); await utils.auth.me.invalidate(); } });
  useEffect(() => { if (user) { setName(user.name || ""); setAvatarUrl((user as typeof user & { avatarUrl?: string | null }).avatarUrl || ""); } }, [user]);
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#090b10] text-slate-400"><Loader2 className="animate-spin" /></div>;
  if (!isAuthenticated || !user) return <main className="grid min-h-screen place-items-center bg-[#090b10] text-white"><button onClick={() => startLogin()} className="rounded-xl bg-violet-500 px-5 py-3 font-bold">Sign in</button></main>;
  const handleFile = (file?: File) => { if (!file || !file.type.startsWith("image/")) return; const reader = new FileReader(); reader.onload = () => { const dataUrl = String(reader.result); uploadAvatar.mutate({ dataUrl, contentType: file.type as "image/png" | "image/jpeg" | "image/webp" | "image/gif" }); }; reader.readAsDataURL(file); };
  return <main className="min-h-screen bg-[#090b10] px-6 py-10 text-white"><div className="mx-auto max-w-2xl"><button onClick={() => setLocation("/")} className="mb-8 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16} /> Back to workspace</button><div className="rounded-3xl border border-white/10 bg-[#151821] p-8 shadow-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">Your profile</p><h1 className="mt-3 text-3xl font-black">Make it yours.</h1><p className="mt-2 text-sm text-slate-400">Your name and avatar appear across servers and direct messages.</p><div className="mt-8 flex items-center gap-5"><button onClick={() => fileRef.current?.click()} className="group relative grid h-24 w-24 place-items-center overflow-hidden rounded-3xl bg-violet-400 text-2xl font-black text-slate-950"><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp,image/gif" className="hidden" onChange={event => handleFile(event.target.files?.[0])} />{avatarUrl ? <img src={avatarUrl} alt="Profile avatar" className="h-full w-full object-cover" /> : <>{(name || user.email || "M").slice(0, 1).toUpperCase()}<span className="absolute inset-0 grid place-items-center bg-black/50 opacity-0 transition group-hover:opacity-100"><ImagePlus size={22} className="text-white" /></span></>}</button><div><p className="font-semibold text-white">{name || user.email}</p><p className="mt-1 text-xs text-emerald-400">Online</p><button onClick={() => fileRef.current?.click()} className="mt-2 text-xs text-violet-300 hover:text-violet-200">Choose a new avatar</button></div></div><label className="mt-8 block text-xs font-bold uppercase tracking-widest text-slate-500">Display name<input value={name} onChange={event => setName(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0d0f15] px-4 py-3 text-sm text-white outline-none focus:border-violet-400" placeholder="Your display name" /></label><label className="mt-5 block text-xs font-bold uppercase tracking-widest text-slate-500">Avatar URL <span className="font-normal normal-case tracking-normal text-slate-600">(optional)</span><input value={avatarUrl} onChange={event => setAvatarUrl(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0d0f15] px-4 py-3 text-sm text-white outline-none focus:border-violet-400" placeholder="https://…" /></label><button onClick={() => update.mutate({ name: name.trim() || "Member", avatarUrl })} disabled={update.isPending || uploadAvatar.isPending} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-violet-500 px-5 py-3 text-sm font-bold hover:bg-violet-400 disabled:opacity-50">{update.isPending ? <Loader2 size={16} className="animate-spin" /> : <Check size={16} />} Save profile</button></div></div></main>;
}
