import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Camera, CameraOff, Loader2, Mic, MicOff, MonitorUp, PhoneOff, Users, Video } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useLocation, useParams } from "wouter";

function RemoteVideo({ stream, label }: { stream: MediaStream; label: string }) {
  const ref = useRef<HTMLVideoElement>(null);
  useEffect(() => { if (ref.current) { ref.current.srcObject = stream; void ref.current.play().catch(() => undefined); } }, [stream]);
  return <div className="relative overflow-hidden rounded-xl bg-black"><video ref={ref} playsInline className="aspect-video w-full object-cover" /><span className="absolute bottom-2 left-2 rounded bg-black/60 px-2 py-1 text-xs text-white">{label}</span></div>;
}

export default function Voice() {
  const { user, loading, isAuthenticated } = useAuth();
  const { serverId, channelId } = useParams<{ serverId: string; channelId: string }>();
  const [, setLocation] = useLocation();
  const numericServerId = Number(serverId); const numericChannelId = Number(channelId);
  const [cameraOn, setCameraOn] = useState(true); const [micOn, setMicOn] = useState(true); const [screenSharing, setScreenSharing] = useState(false); const [joined, setJoined] = useState(false); const [roomId, setRoomId] = useState<number | null>(null); const [error, setError] = useState(""); const [remoteStreams, setRemoteStreams] = useState<Record<number, MediaStream>>({});
  const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null); const screenRef = useRef<MediaStream | null>(null); const peersRef = useRef<Record<number, RTCPeerConnection>>({});
  const utils = trpc.useUtils(); const { data: iceServers = [{ urls: "stun:stun.l.google.com:19302" }] } = trpc.voice.iceServers.useQuery();
  const { data: participants = [] } = trpc.voice.participants.useQuery({ channelId: numericChannelId }, { enabled: isAuthenticated && numericChannelId > 0, refetchInterval: 2000 });
  const sendSignal = trpc.voice.sendSignal.useMutation();
  const pollSignals = trpc.voice.pollSignals.useMutation();
  const join = trpc.voice.join.useMutation();
  const leave = trpc.voice.leave.useMutation({ onSuccess: () => { Object.values(peersRef.current).forEach(peer => peer.close()); peersRef.current = {}; streamRef.current?.getTracks().forEach(track => track.stop()); setJoined(false); setLocation("/"); } });

  const setupMedia = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: true }); streamRef.current = stream; if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); } } catch { setError("Camera or microphone permission was denied. You can still join listen-only."); } };
  useEffect(() => { if (isAuthenticated) void setupMedia(); return () => { streamRef.current?.getTracks().forEach(track => track.stop()); screenRef.current?.getTracks().forEach(track => track.stop()); Object.values(peersRef.current).forEach(peer => peer.close()); }; }, [isAuthenticated]);

  const ensurePeer = (peerUserId: number) => { if (peersRef.current[peerUserId]) return peersRef.current[peerUserId]; const peer = new RTCPeerConnection({ iceServers }); streamRef.current?.getTracks().forEach(track => peer.addTrack(track, streamRef.current!)); peer.onicecandidate = event => { if (event.candidate && roomId) sendSignal.mutate({ roomId, recipientId: peerUserId, type: "ice", payload: JSON.stringify(event.candidate) }); }; peer.ontrack = event => { const stream = event.streams[0]; if (stream) setRemoteStreams(current => ({ ...current, [peerUserId]: stream })); }; peer.onconnectionstatechange = () => { if (["failed", "closed", "disconnected"].includes(peer.connectionState)) { peer.close(); delete peersRef.current[peerUserId]; setRemoteStreams(current => { const next = { ...current }; delete next[peerUserId]; return next; }); } }; peersRef.current[peerUserId] = peer; return peer; };
  const callPeer = async (peerUserId: number, activeRoomId: number) => { if (!user || user.id >= peerUserId) return; const peer = ensurePeer(peerUserId); const offer = await peer.createOffer(); await peer.setLocalDescription(offer); sendSignal.mutate({ roomId: activeRoomId, recipientId: peerUserId, type: "offer", payload: JSON.stringify(offer) }); };
  const handleSignal = async (signal: { senderId: number; type: string; payload: string }) => { const peer = ensurePeer(signal.senderId); if (signal.type === "offer") { await peer.setRemoteDescription(JSON.parse(signal.payload)); const answer = await peer.createAnswer(); await peer.setLocalDescription(answer); if (roomId) sendSignal.mutate({ roomId, recipientId: signal.senderId, type: "answer", payload: JSON.stringify(answer) }); } else if (signal.type === "answer") await peer.setRemoteDescription(JSON.parse(signal.payload)); else if (signal.type === "ice") await peer.addIceCandidate(JSON.parse(signal.payload)); };
  useEffect(() => { if (!joined || !roomId) return; const timer = window.setInterval(() => { pollSignals.mutate({ roomId }, { onSuccess: signals => signals.forEach(signal => void handleSignal(signal)) }); }, 800); return () => window.clearInterval(timer); }, [joined, roomId]);
  useEffect(() => { if (!joined || !roomId || !user) return; participants.filter(participant => participant.userId !== user.id && participant.userId > user.id && !peersRef.current[participant.userId]).forEach(participant => void callPeer(participant.userId, roomId)); }, [participants, joined, roomId, user]);

  const joinRoom = () => { join.mutate({ serverId: numericServerId, channelId: numericChannelId, cameraOn, micOn, screenSharing }, { onSuccess: result => { setRoomId(result.roomId); setJoined(true); } }); };
  const toggleCamera = () => { const next = !cameraOn; streamRef.current?.getVideoTracks().forEach(track => { track.enabled = next; }); setCameraOn(next); };
  const toggleMic = () => { const next = !micOn; streamRef.current?.getAudioTracks().forEach(track => { track.enabled = next; }); setMicOn(next); };
  const toggleScreen = async () => { if (screenSharing) { screenRef.current?.getTracks().forEach(track => track.stop()); screenRef.current = null; if (videoRef.current && streamRef.current) videoRef.current.srcObject = streamRef.current; setScreenSharing(false); return; } try { const screen = await navigator.mediaDevices.getDisplayMedia({ video: true, audio: true }); screenRef.current = screen; if (videoRef.current) { videoRef.current.srcObject = screen; await videoRef.current.play(); } setScreenSharing(true); screen.getVideoTracks()[0].onended = () => { setScreenSharing(false); if (videoRef.current && streamRef.current) videoRef.current.srcObject = streamRef.current; }; } catch { setError("Screen sharing was cancelled."); } };
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#090b10] text-slate-400"><Loader2 className="animate-spin" /></div>;
  if (!isAuthenticated || !user) return <main className="grid min-h-screen place-items-center bg-[#090b10] text-white"><button onClick={() => startLogin()} className="rounded-xl bg-violet-500 px-5 py-3 font-bold">Sign in</button></main>;
  return <main className="min-h-screen bg-[#090b10] px-3 py-5 text-white sm:px-6 sm:py-8"><div className="mx-auto max-w-5xl"><button onClick={() => setLocation("/")} className="mb-5 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16} /> Back</button><div className="rounded-3xl border border-white/10 bg-[#151821] p-4 shadow-2xl sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">Voice + video</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">Huddle room</h1><p className="mt-2 text-sm text-slate-400">Peer-to-peer media with database signaling and optional TURN.</p></div><div className="flex items-center gap-2 text-sm text-slate-400"><Users size={17} /> {participants.length} present</div></div>{error && <p className="mt-5 rounded-xl border border-amber-400/20 bg-amber-400/10 px-4 py-3 text-sm text-amber-200">{error}</p>}<div className="mt-6 grid gap-4 md:grid-cols-2">{joined && Object.entries(remoteStreams).map(([id, stream]) => <RemoteVideo key={id} stream={stream} label={participants.find(participant => participant.userId === Number(id))?.name || "Member"} />)}<div className="overflow-hidden rounded-2xl bg-black"><video ref={videoRef} muted playsInline className="aspect-video w-full object-cover" /><div className="flex flex-wrap items-center justify-center gap-2 border-t border-white/10 bg-[#0d0f15] p-3 sm:gap-3 sm:p-4"><button onClick={toggleMic} className={`grid h-10 w-10 place-items-center rounded-full ${micOn ? "bg-slate-700" : "bg-rose-500"}`}>{micOn ? <Mic size={17} /> : <MicOff size={17} />}</button><button onClick={toggleCamera} className={`grid h-10 w-10 place-items-center rounded-full ${cameraOn ? "bg-slate-700" : "bg-rose-500"}`}>{cameraOn ? <Camera size={17} /> : <CameraOff size={17} />}</button><button onClick={toggleScreen} className={`grid h-10 w-10 place-items-center rounded-full ${screenSharing ? "bg-violet-500" : "bg-slate-700"}`}><MonitorUp size={17} /></button>{joined ? <button onClick={() => leave.mutate({ channelId: numericChannelId })} className="grid h-10 w-10 place-items-center rounded-full bg-rose-500"><PhoneOff size={17} /></button> : <button onClick={joinRoom} className="rounded-full bg-emerald-500 px-4 py-2.5 text-sm font-bold">Join room</button>}</div></div></div><div className="mt-5 rounded-xl border border-violet-400/10 bg-violet-400/5 p-4"><Video size={18} className="text-violet-300" /><p className="mt-2 text-xs leading-5 text-slate-400">Remote audio/video uses WebRTC. For users behind restrictive networks, configure TURN_URL, TURN_USERNAME, and TURN_CREDENTIAL on the server.</p></div></div></div></main>;
}
