import { and, eq } from "drizzle-orm";
import { nanoid } from "nanoid";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { channels, directMessages, invites, messageReactions, messages, moderationActions, notifications, pushSubscriptions, servers, serverMembers, users, voiceParticipants, voiceRooms, voiceSignals } from "../drizzle/schema";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { getDb, getDirectMessages, getInvite, getMembersForServer, getMessagesForChannel, getNotifications, getPublicUser, getRecentDirectContacts, getServersForUser, getVoiceParticipants, getVoiceSignals, isChannelMember, isServerMember, isServerModerator } from "./db";
import { storagePut } from "./storage";
import webpush from "web-push";

const requireDb = async () => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); return db; };
const attachmentInput = z.object({ dataUrl: z.string().startsWith("data:").max(12_000_000), fileName: z.string().trim().min(1).max(255), contentType: z.string().max(120), size: z.number().int().positive().max(8_000_000) });
async function putAttachment(userId: number, input: z.infer<typeof attachmentInput>) { const [, encoded] = input.dataUrl.split(","); if (!encoded) throw new TRPCError({ code: "BAD_REQUEST", message: "Invalid attachment data" }); const result = await storagePut(`attachments/${userId}/${nanoid(10)}-${input.fileName.replace(/[^a-zA-Z0-9._-]/g, "_")}`, Buffer.from(encoded, "base64"), input.contentType || "application/octet-stream"); return { ...input, url: result.url }; }
if (process.env.VAPID_PUBLIC_KEY && process.env.VAPID_PRIVATE_KEY && process.env.VAPID_EMAIL) webpush.setVapidDetails(`mailto:${process.env.VAPID_EMAIL}`, process.env.VAPID_PUBLIC_KEY, process.env.VAPID_PRIVATE_KEY);
async function sendPush(db: Awaited<ReturnType<typeof requireDb>>, userId: number, payload: { title: string; body: string; link?: string }) { if (!process.env.VAPID_PUBLIC_KEY || !process.env.VAPID_PRIVATE_KEY || !process.env.VAPID_EMAIL) return; const subscriptions = await db.select().from(pushSubscriptions).where(eq(pushSubscriptions.userId, userId)); await Promise.allSettled(subscriptions.map(subscription => webpush.sendNotification({ endpoint: subscription.endpoint, keys: { p256dh: subscription.p256dh, auth: subscription.auth } }, JSON.stringify(payload)))); }

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }),
  }),
  profile: router({
    me: protectedProcedure.query(({ ctx }) => ctx.user),
    user: protectedProcedure.input(z.object({ userId: z.number().int().positive() })).query(({ input }) => getPublicUser(input.userId)),
    update: protectedProcedure.input(z.object({ name: z.string().trim().min(1).max(80), avatarUrl: z.string().url().max(512).optional().or(z.literal("")) })).mutation(async ({ ctx, input }) => { const db = await requireDb(); await db.update(users).set({ name: input.name, avatarUrl: input.avatarUrl || null }).where(eq(users.id, ctx.user.id)); return { success: true } as const; }),
    uploadAvatar: protectedProcedure.input(z.object({ dataUrl: z.string().startsWith("data:image/").max(7_000_000), contentType: z.enum(["image/png", "image/jpeg", "image/webp", "image/gif"]) })).mutation(async ({ ctx, input }) => { const [, encoded] = input.dataUrl.split(","); if (!encoded) throw new TRPCError({ code: "BAD_REQUEST", message: "Invalid image data" }); const result = await storagePut(`avatars/${ctx.user.id}-${nanoid(8)}`, Buffer.from(encoded, "base64"), input.contentType); const db = await requireDb(); await db.update(users).set({ avatarUrl: result.url }).where(eq(users.id, ctx.user.id)); return { url: result.url }; }),
  }),
  notifications: router({
    list: protectedProcedure.query(({ ctx }) => getNotifications(ctx.user.id)),
    vapidPublicKey: publicProcedure.query(() => process.env.VAPID_PUBLIC_KEY || null),
    subscribe: protectedProcedure.input(z.object({ endpoint: z.string().url().max(1024), keys: z.object({ p256dh: z.string().min(16), auth: z.string().min(8) }) })).mutation(async ({ ctx, input }) => { const db = await requireDb(); const existing = (await db.select().from(pushSubscriptions).where(and(eq(pushSubscriptions.userId, ctx.user.id), eq(pushSubscriptions.endpoint, input.endpoint))).limit(1))[0]; if (existing) await db.update(pushSubscriptions).set({ p256dh: input.keys.p256dh, auth: input.keys.auth }).where(eq(pushSubscriptions.id, existing.id)); else await db.insert(pushSubscriptions).values({ userId: ctx.user.id, endpoint: input.endpoint, p256dh: input.keys.p256dh, auth: input.keys.auth }); return { success: true } as const; }),
    unsubscribe: protectedProcedure.input(z.object({ endpoint: z.string().url().max(1024) })).mutation(async ({ ctx, input }) => { const db = await requireDb(); await db.delete(pushSubscriptions).where(and(eq(pushSubscriptions.userId, ctx.user.id), eq(pushSubscriptions.endpoint, input.endpoint))); return { success: true } as const; }),
    markRead: protectedProcedure.input(z.object({ notificationId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await requireDb(); await db.update(notifications).set({ readAt: new Date() }).where(and(eq(notifications.id, input.notificationId), eq(notifications.userId, ctx.user.id))); return { success: true } as const; }),
    markAllRead: protectedProcedure.mutation(async ({ ctx }) => { const db = await requireDb(); await db.update(notifications).set({ readAt: new Date() }).where(eq(notifications.userId, ctx.user.id)); return { success: true } as const; }),
  }),
  community: router({
    listServers: protectedProcedure.query(({ ctx }) => getServersForUser(ctx.user.id)),
    members: protectedProcedure.input(z.object({ serverId: z.number().int().positive() })).query(({ ctx, input }) => getMembersForServer(ctx.user.id, input.serverId)),
    messages: protectedProcedure.input(z.object({ channelId: z.number().int().positive() })).query(({ ctx, input }) => getMessagesForChannel(ctx.user.id, input.channelId)),
    createServer: protectedProcedure.input(z.object({ name: z.string().trim().min(2).max(48) })).mutation(async ({ ctx, input }) => { const db = await requireDb(); const inserted = await db.insert(servers).values({ name: input.name, icon: input.name.slice(0, 1).toUpperCase(), ownerId: ctx.user.id }); const serverId = Number((inserted as any).insertId); await db.insert(serverMembers).values({ serverId, userId: ctx.user.id, role: "owner" }); await db.insert(channels).values({ serverId, name: "general" }); return { serverId }; }),
    createChannel: protectedProcedure.input(z.object({ serverId: z.number().int().positive(), name: z.string().trim().min(2).max(48) })).mutation(async ({ ctx, input }) => { if (!(await isServerModerator(ctx.user.id, input.serverId))) throw new TRPCError({ code: "FORBIDDEN", message: "Only server moderators can create channels" }); const db = await requireDb(); const inserted = await db.insert(channels).values({ serverId: input.serverId, name: input.name.replace(/\s+/g, "-").toLowerCase() }); return { channelId: Number((inserted as any).insertId) }; }),
    sendMessage: protectedProcedure.input(z.object({ channelId: z.number().int().positive(), content: z.string().trim().min(1).max(2000) })).mutation(async ({ ctx, input }) => { if (!(await isChannelMember(ctx.user.id, input.channelId))) throw new TRPCError({ code: "FORBIDDEN", message: "You cannot post in this channel" }); const db = await requireDb(); await db.insert(messages).values({ channelId: input.channelId, userId: ctx.user.id, content: input.content }); return { success: true } as const; }),
    sendAttachment: protectedProcedure.input(z.object({ channelId: z.number().int().positive(), content: z.string().max(2000).default(""), attachment: attachmentInput })).mutation(async ({ ctx, input }) => { if (!(await isChannelMember(ctx.user.id, input.channelId))) throw new TRPCError({ code: "FORBIDDEN", message: "You cannot post in this channel" }); const db = await requireDb(); const uploaded = await putAttachment(ctx.user.id, input.attachment); await db.insert(messages).values({ channelId: input.channelId, userId: ctx.user.id, content: input.content, attachmentUrl: uploaded.url, attachmentName: uploaded.fileName, attachmentType: uploaded.contentType, attachmentSize: uploaded.size }); return { success: true, url: uploaded.url } as const; }),
    createInvite: protectedProcedure.input(z.object({ serverId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { if (!(await isServerMember(ctx.user.id, input.serverId))) throw new TRPCError({ code: "FORBIDDEN" }); const db = await requireDb(); const code = nanoid(10); await db.insert(invites).values({ serverId: input.serverId, code, createdBy: ctx.user.id, expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) }); return { code }; }),
    joinInvite: protectedProcedure.input(z.object({ code: z.string().trim().min(4).max(24) })).mutation(async ({ ctx, input }) => { const invite = await getInvite(input.code); if (!invite || (invite.expiresAt && invite.expiresAt < new Date())) throw new TRPCError({ code: "NOT_FOUND", message: "Invite expired or not found" }); const db = await requireDb(); if (!(await isServerMember(ctx.user.id, invite.serverId))) { await db.insert(serverMembers).values({ serverId: invite.serverId, userId: ctx.user.id, role: "member" }); await db.update(invites).set({ uses: invite.uses + 1 }).where(eq(invites.id, invite.id)); } return { serverId: invite.serverId }; }),
    setMemberRole: protectedProcedure.input(z.object({ serverId: z.number().int().positive(), userId: z.number().int().positive(), role: z.enum(["moderator", "member"]) })).mutation(async ({ ctx, input }) => { if (!(await isServerModerator(ctx.user.id, input.serverId))) throw new TRPCError({ code: "FORBIDDEN" }); const db = await requireDb(); await db.update(serverMembers).set({ role: input.role }).where(and(eq(serverMembers.serverId, input.serverId), eq(serverMembers.userId, input.userId))); return { success: true } as const; }),
    toggleReaction: protectedProcedure.input(z.object({ messageId: z.number().int().positive(), emoji: z.string().min(1).max(16) })).mutation(async ({ ctx, input }) => { const db = await requireDb(); const existing = (await db.select().from(messageReactions).where(and(eq(messageReactions.messageId, input.messageId), eq(messageReactions.userId, ctx.user.id), eq(messageReactions.emoji, input.emoji))).limit(1))[0]; if (existing) await db.delete(messageReactions).where(eq(messageReactions.id, existing.id)); else await db.insert(messageReactions).values({ messageId: input.messageId, userId: ctx.user.id, emoji: input.emoji }); return { success: true } as const; }),
    deleteMessage: protectedProcedure.input(z.object({ messageId: z.number().int().positive(), serverId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { if (!(await isServerModerator(ctx.user.id, input.serverId))) throw new TRPCError({ code: "FORBIDDEN", message: "Only moderators can delete messages" }); const db = await requireDb(); await db.delete(messages).where(eq(messages.id, input.messageId)); await db.insert(moderationActions).values({ serverId: input.serverId, moderatorId: ctx.user.id, messageId: input.messageId, action: "delete_message", reason: "Deleted by moderator" }); return { success: true } as const; }),
  }),
  direct: router({
    contacts: protectedProcedure.query(({ ctx }) => getRecentDirectContacts(ctx.user.id)),
    messages: protectedProcedure.input(z.object({ otherUserId: z.number().int().positive() })).query(({ ctx, input }) => getDirectMessages(ctx.user.id, input.otherUserId)),
    send: protectedProcedure.input(z.object({ recipientId: z.number().int().positive(), content: z.string().trim().min(1).max(2000) })).mutation(async ({ ctx, input }) => { if (input.recipientId === ctx.user.id) throw new TRPCError({ code: "BAD_REQUEST", message: "You cannot message yourself" }); const db = await requireDb(); await db.insert(directMessages).values({ senderId: ctx.user.id, recipientId: input.recipientId, content: input.content }); await db.insert(notifications).values({ userId: input.recipientId, type: "direct_message", title: "New direct message", body: input.content.slice(0, 160), link: `/dm/${ctx.user.id}` }); await sendPush(db, input.recipientId, { title: "New direct message", body: input.content.slice(0, 160), link: `/dm/${ctx.user.id}` }); return { success: true } as const; }),
    sendAttachment: protectedProcedure.input(z.object({ recipientId: z.number().int().positive(), content: z.string().max(2000).default(""), attachment: attachmentInput })).mutation(async ({ ctx, input }) => { if (input.recipientId === ctx.user.id) throw new TRPCError({ code: "BAD_REQUEST", message: "You cannot message yourself" }); const db = await requireDb(); const uploaded = await putAttachment(ctx.user.id, input.attachment); await db.insert(directMessages).values({ senderId: ctx.user.id, recipientId: input.recipientId, content: input.content, attachmentUrl: uploaded.url, attachmentName: uploaded.fileName, attachmentType: uploaded.contentType, attachmentSize: uploaded.size }); await db.insert(notifications).values({ userId: input.recipientId, type: "direct_attachment", title: "New attachment", body: uploaded.fileName, link: `/dm/${ctx.user.id}` }); await sendPush(db, input.recipientId, { title: "New attachment", body: uploaded.fileName, link: `/dm/${ctx.user.id}` }); return { success: true, url: uploaded.url } as const; }),
  }),
  voice: router({
    iceServers: publicProcedure.query(async () => { if (process.env.TURN_KEY_ID && process.env.TURN_API_TOKEN) { const response = await fetch(`https://rtc.live.cloudflare.com/v1/turn/keys/${process.env.TURN_KEY_ID}/credentials/generate-ice-servers`, { method: "POST", headers: { Authorization: `Bearer ${process.env.TURN_API_TOKEN}`, "Content-Type": "application/json" }, body: JSON.stringify({ ttl: 86400 }) }); if (response.ok) { const payload = await response.json() as { iceServers?: Array<{ urls: string | string[]; username?: string; credential?: string }> }; if (payload.iceServers?.length) return payload.iceServers; } } const servers: Array<{ urls: string | string[]; username?: string; credential?: string }> = [{ urls: "stun:stun.cloudflare.com:3478" }]; if (process.env.TURN_URL && process.env.TURN_USERNAME && process.env.TURN_CREDENTIAL) servers.push({ urls: process.env.TURN_URL, username: process.env.TURN_USERNAME, credential: process.env.TURN_CREDENTIAL }); return servers; }),
    participants: protectedProcedure.input(z.object({ channelId: z.number().int().positive() })).query(({ ctx, input }) => getVoiceParticipants(ctx.user.id, input.channelId)),
    sendSignal: protectedProcedure.input(z.object({ roomId: z.number().int().positive(), recipientId: z.number().int().positive(), type: z.enum(["offer", "answer", "ice", "leave"]), payload: z.string().max(100_000) })).mutation(async ({ ctx, input }) => { const db = await requireDb(); await db.insert(voiceSignals).values({ roomId: input.roomId, senderId: ctx.user.id, recipientId: input.recipientId, type: input.type, payload: input.payload }); return { success: true } as const; }),
    pollSignals: protectedProcedure.input(z.object({ roomId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await requireDb(); const signals = await getVoiceSignals(ctx.user.id, input.roomId); if (signals.length) await db.delete(voiceSignals).where(and(eq(voiceSignals.roomId, input.roomId), eq(voiceSignals.recipientId, ctx.user.id))); return signals; }),
    join: protectedProcedure.input(z.object({ serverId: z.number().int().positive(), channelId: z.number().int().positive(), cameraOn: z.boolean(), micOn: z.boolean(), screenSharing: z.boolean() })).mutation(async ({ ctx, input }) => { if (!(await isChannelMember(ctx.user.id, input.channelId))) throw new TRPCError({ code: "FORBIDDEN" }); const db = await requireDb(); let room = (await db.select().from(voiceRooms).where(eq(voiceRooms.channelId, input.channelId)).limit(1))[0]; if (!room) { const inserted = await db.insert(voiceRooms).values({ serverId: input.serverId, channelId: input.channelId }); room = (await db.select().from(voiceRooms).where(eq(voiceRooms.id, Number((inserted as any).insertId))).limit(1))[0]; } if (!room) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const existing = (await db.select().from(voiceParticipants).where(and(eq(voiceParticipants.roomId, room.id), eq(voiceParticipants.userId, ctx.user.id))).limit(1))[0]; const values = { roomId: room.id, userId: ctx.user.id, cameraOn: input.cameraOn ? 1 : 0, micOn: input.micOn ? 1 : 0, screenSharing: input.screenSharing ? 1 : 0, lastSeenAt: new Date() }; if (existing) await db.update(voiceParticipants).set(values).where(eq(voiceParticipants.id, existing.id)); else await db.insert(voiceParticipants).values(values); return { roomId: room.id } }),
    leave: protectedProcedure.input(z.object({ channelId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await requireDb(); const room = (await db.select().from(voiceRooms).where(eq(voiceRooms.channelId, input.channelId)).limit(1))[0]; if (room) await db.delete(voiceParticipants).where(and(eq(voiceParticipants.roomId, room.id), eq(voiceParticipants.userId, ctx.user.id))); return { success: true } as const; }),
  }),
});
export type AppRouter = typeof appRouter;
